### ISSUE TITLE
Importation Base Mysql dans PhpMyadmin

### ISSUE THREAD

**Issue by andynosaur** [ymairesse/ZeusEdu#3]
Bonjour, 

merci pour ton travail, qui facilite grandement la vie !

J'ai eu un petit probleme récemment : lors de l'importation de ZeusEdu.sql dans PhpMyAdmin comme nouvelle base de données, j'ai un message d'erreur qui me dit que la syntaxe n'est pas correct : 

`<!DOCTYPE html> <html lang="en" class=" is-copy-enabled emoji-size-boost"> <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#"> <meta charset='utf-8'> <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/frameworks-d05617edbd0684501ca011b9998eb456541d8156ca96d8ffcfb175827827f62c.css" integrity="sha256-0FYX7b0GhFAcoBG5mY60VlQdgVbKltj/z7F1gngn9iw=" media="all" rel="stylesheet" /> <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/github-a5740f61dda90caedf6fe1f31c4049c578b906cca54de55bb297aff18eb0ff08.css" integrity="sha256-pXQPYd2pDK7fb+HzHEBJxXi5BsylTeVbspev8Y6w/wg=" media="all" rel="stylesheet" /> <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/site-0996ced1a40a04be84d932b2c830830a2c87259cfb5c41c90ca7fee0c5979e9d.css" integrity="sha256-CZbO0aQKBL6E2TKyyDCDCiyHJZz7XEHJDKf+4MWXn[...] `

ET

`#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<!DOCTYPE html>
<html lang="en" class=" is-copy-enabled emoji-size-boost">
  <he' at line 1 `

Je ne sais pas si c'est normal, j'ai essayé de checker la ligne 1, mais je n'ai pas assez de compétence à ce niveau là je crois.

Est-ce normal ?
Sinon, ai-je fais une mauvaise manip ?

Merci d'avance pour la réponse.
A bientôt.

Andy.

**Comment by ymairesse** [comment]
Bonjour

Effectivement, voilà un souci.
J'essaie de comprendre, mais je ne vois pas trop ce que vient faire 
http://ogp.me dans le code.
En tous les cas, ce n'est pas dans le code source "officiel".
Est-ce disponible en ligne quelque part?

Par contre, il y a eu tout récemment une petite modification dans la 
base de données, dans la table didac_profs.
Un champ a été ajouté dans cette table.
Mais il n'y a, a priori, pas de rapport avec le code bizarre observé là.

Bien cordialement.

Yves Mairesse

**Comment by andynosaur** [comment]
Le fichier ZeusEdu.sql viens de ce GitHub :-)
C'est pour cela que ca me paraissait étrange...

**Comment by andynosaur** [comment]
Bon a priori, j'ai compris le probleme...
Je prenait le fichier d'une mauvaise facon qu'il se modifiait au téléchargement.
Désolé pour cette erreur très Noob.

Bon, il y a une autre erreur de Base non trouvée, mais je vais cherché d'abord !

**Comment by ymairesse** [comment]
Le nom de la base de données n'a pas d'importance; mais elle doit exister.
Il faut donc la créer avant d'injecter le fichier .sql.

J'ai commencé à mettre au point une procédure d'installation. Mais pas 
sûr qu'elle fonctionne. Je n'ai plus eu le temps d'y toucher.
/install/index.php
Je peux m'y recoller, mais pas dans les jours qui viennent.

Yves Mairesse

**Comment by andynosaur** [comment]
Ah oui, ok, je pensais qu'elle se créait d'elle même.

Et oui, le mois de juin doit être bien chargé j'imagine !
Merci pour tout !

**Comment by ymairesse** [comment]
Merci de continuer de me faire part d'éventuelles difficultés et/ou de 
revenir avec des questions et des suggestions.
